Repository HUFS-Algoing/Algoing-FE, pull requests merged in 2025-05, with the labels that each got.

#10 [✨ Feature] 메인 페이지 UI 구현
  package.json
  pnpm-lock.yaml
  public/DarkModeLogo.png
  public/LightModeLogo.png
  public/logo.png
  public/profile5.png
  src/app/(with-header)/ai-review/[id]/page.tsx
  src/app/(with-header)/ai-review/components/ai-code-review-list.tsx
  src/app/(with-header)/ai-review/layout.tsx
  src/app/(with-header)/ai-review/page.tsx
  src/app/(with-header)/community/components/code-editor.tsx
  src/app/(with-header)/community/components/code-reivew-detail.tsx
  src/app/(with-header)/community/components/code-review-community.tsx
  src/app/(with-header)/community/components/comment-editor.tsx
  src/app/(with-header)/community/components/community-header.tsx
  src/app/(with-header)/community/layout.tsx
  src/app/(with-header)/community/page.tsx
  src/app/(with-header)/community/post/[id]/page.tsx
  src/app/(with-header)/layout.tsx
  src/app/(with-header)/main/components/Calendar.tsx
  src/app/(with-header)/main/components/Progress.tsx
  src/app/(with-header)/main/components/Recommend.tsx
  src/app/(with-header)/main/page.tsx
  src/app/(with-header)/mypage/page.tsx
  src/app/(with-header)/recommend/components/carousel.tsx
  src/app/(with-header)/recommend/components/problem-card.tsx
  src/app/(with-header)/recommend/page.tsx
  src/app/_components/DarkMode.tsx
  src/app/_components/Header.tsx
  src/app/_types/prismjs.ts
  src/app/globals.css
  src/app/lib/utils.ts
  tailwind.config.ts
Labels: 🎨 Desgin, ✨ Feature

#12 feat: 프로필 설정 UI 구현
  src/app/(no-header)/profile/page.tsx
Labels: 🎨 Desgin

#14 [Fix/#13] 빌드오류 해결, type, mock 폴더분리
  src/app/(with-header)/ai-review/[id]/page.tsx
  src/app/(with-header)/ai-review/components/ai-code-review-list.tsx
  src/app/(with-header)/community/components/code-reivew-detail.tsx
  src/app/(with-header)/community/components/code-review-community.tsx
  src/app/(with-header)/community/post/[id]/page.tsx
  src/app/(with-header)/mypage/page.tsx
  src/app/(with-header)/recommend/components/problem-card.tsx
  src/app/(with-header)/recommend/page.tsx
  src/app/_components/Header.tsx
  src/app/_mock/ai-review.ts
  src/app/_mock/code-review.ts
  src/app/_mock/mypage.ts
  src/app/_mock/recommend.ts
  src/app/_mock/user-data.ts
  src/app/_types/.gitkeep
  src/app/_types/ai-review.ts
  src/app/_types/code-review-post.ts
  src/app/_types/mypage.ts
  src/app/_types/prismjs.ts
  tsconfig.json
Labels: 🐞 BugFix, 🌏 Deploy
