Repository HUFS-Algoing/Algoing-FE, pull requests merged in 2025-06, with the labels that each got.

#23 [Feature/19] 문제추천 API 연결
  .github/pull_request_template.md
  package.json
  pnpm-lock.yaml
  src/app/(no-header)/login/page.tsx
  src/app/(no-header)/profile/page.tsx
  src/app/(with-header)/code/components/code/CodeHeader.tsx
  src/app/(with-header)/code/components/code/CodeReview.tsx
  src/app/(with-header)/layout.tsx
  src/app/(with-header)/main/components/Recommend.tsx
  src/app/(with-header)/main/page.tsx
  src/app/(with-header)/mypage/page.tsx
  src/app/(with-header)/page.tsx
  src/app/(with-header)/recommend/(problems)/incproblem-recommend.tsx
  src/app/(with-header)/recommend/(problems)/tier-based-recommend.tsx
  src/app/(with-header)/recommend/(problems)/weakness-recommend.tsx
  src/app/(with-header)/recommend/components/intro-section.tsx
  src/app/(with-header)/recommend/components/problem-card.tsx
  src/app/(with-header)/recommend/components/recommend-content.tsx
  src/app/(with-header)/recommend/page.tsx
  src/app/_api/recommend/get-daily-problems.ts
  src/app/_api/recommend/get-incproblems.ts
  src/app/_api/recommend/get-weakness-problems.ts
  src/app/_components/Header.tsx
  src/app/_types/recommend.ts
  src/app/hook/recommend/use-incproblem.ts
  src/app/hook/recommend/use-tier-based.ts
  src/app/hook/recommend/use-weakness.ts
  src/app/layout.tsx
  src/app/providers.tsx
  tailwind.config.ts
Labels: 📬 API, ✨ Feature

#25 [Bug/24] 자동배포 workflow 추가
  .github/pull_request_template.md
  .github/workflows/deploy.yml
Labels: 🌏 Deploy, ⚙ Setting

#27 [Feature/26] huksy 추가
  .github/auto_assign.yml
  .github/workflows/action.yml
  .husky/pre-commit
  package.json
  pnpm-lock.yaml
  src/app/(with-header)/mypage/page.tsx
Labels: ⚙ Setting

#36 [Feature/34] 추천문제 API 변경
  src/app/(with-header)/main/components/Recommend.tsx
  src/app/(with-header)/recommend/components/intro-section.tsx
  src/app/(with-header)/recommend/components/recommend-content.tsx
  src/app/(with-header)/recommend/components/recommend-section.tsx
  src/app/(with-header)/recommend/page.tsx
  src/app/_api/recommend/get-all.ts
  src/app/_types/recommend.ts
  src/app/hook/recommend/use-all-recommend.ts
Labels: 📬 API

#38 [Feature/35] 코드 제출, 리뷰, 힌트 api 연동
  src/app/(with-header)/code/[id]/page.tsx
  src/app/(with-header)/code/components/code/CodeEditor.tsx
  src/app/(with-header)/code/components/code/CodeReview.tsx
  src/app/(with-header)/code/components/code/Footer.tsx
  src/app/(with-header)/main/components/Recommend.tsx
  src/app/_api/problem/getHint.ts
  src/app/_api/problem/problemSubmit.ts
  src/app/_api/recommend/post-recommend-click.ts
  src/app/_api/review/post-review.ts
  src/app/_types/recommend.ts
  src/app/hook/problem/use-getHint.ts
  src/app/hook/problem/use-problem-submit.ts
  src/app/hook/recommend/use-log-click.ts
  src/app/hook/review/use-review.ts
Labels: 📬 API

#46 [Feature/#45] snapshot API로 통계 시각화
  next.config.ts
  package.json
  pnpm-lock.yaml
  src/app/(with-header)/main/components/Calendar.tsx
  src/app/(with-header)/mypage/components/activity-chart.tsx
  src/app/(with-header)/mypage/components/code-chart.tsx
  src/app/(with-header)/mypage/components/performance-chart.tsx
  src/app/(with-header)/mypage/components/problem-tabs.tsx
  src/app/(with-header)/mypage/components/stats-cards.tsx
  src/app/(with-header)/mypage/components/tag-chart.tsx
  src/app/(with-header)/mypage/page.tsx
  src/app/_types/snapshot.ts
  src/app/hook/use-snapshot.ts
  src/app/hook/use-zandi.ts
Labels: 📬 API, 🎨 Desgin

#47 [fix/build] 빌드에러 해결
  pnpm-lock.yaml
Labels: 🐞 BugFix

#52 [Feature/50] 탭 제출내역 모달추가
  src/app/(with-header)/mypage/components/(problem-tabs)/bookmarked-card.tsx
  src/app/(with-header)/mypage/components/(problem-tabs)/problem-modal.tsx
  src/app/(with-header)/mypage/components/(problem-tabs)/submitted-card.tsx
  src/app/(with-header)/mypage/components/problem-tabs.tsx
  src/app/(with-header)/mypage/components/stats-cards.tsx
  src/app/_types/post.ts
  src/app/_util/get-language-color.ts
  src/app/_util/group-problem-id.ts
Labels: 📬 API, 🎨 Desgin

#54 [Feature/51] 잔디 UI개선, mypage, 검색 CSS 수정
  src/app/(with-header)/main/components/Calendar.tsx
  src/app/(with-header)/main/page.tsx
  src/app/(with-header)/mypage/components/intro-section.tsx
  src/app/(with-header)/mypage/page.tsx
  src/app/(with-header)/recommend/components/recommend-content.tsx
  src/app/(with-header)/recommend/page.tsx
  src/app/_components/Header.tsx
  src/app/_components/Search.tsx
  src/app/_util/color-class.ts
  src/app/_util/date.ts
Labels: 🎨 Desgin

#59 Feat: 북마크 api 연동 코드 제출 결과 ui 수정
  package.json
  pnpm-lock.yaml
  src/app/(with-header)/code/[id]/page.tsx
  src/app/(with-header)/code/components/code/CodeHeader.tsx
  src/app/(with-header)/code/components/code/Footer.tsx
  src/app/(with-header)/code/components/code/ProblemInfo.tsx
  src/app/(with-header)/code/components/code/ResizableCodeEditor.tsx
  src/app/_api/problem/toggle-bookmark.ts
  src/app/_components/ToastProvider.tsx
  src/app/hook/problem/use-bookmark.ts
Labels: 📬 API, 🎨 Desgin

#60 [feature/58] 인트로 스크롤 페이지 구현
  public/img/section.png
  src/app/(no-header)/login/page.tsx
Labels: 🎨 Desgin

#67 [Bug/66] QA google username
  src/app/(with-header)/main/components/Recommend.tsx
  src/app/(with-header)/main/components/UserProfileCard.tsx
  src/app/(with-header)/main/page.tsx
  src/app/(with-header)/recommend/components/recommend-content.tsx
  src/app/(with-header)/recommend/page.tsx
  src/app/_api/user/getMyInfo.ts
  src/app/_components/Header.tsx
  src/app/_mock/myinfo.ts
  src/app/_store/use-userStore.ts
Labels: 🐞 BugFix, 🔄 Refactor

#69 [Bug/68] 스크롤이슈 해결, emptyUI추가, 로그아웃API
  src/app/(with-header)/main/components/Calendar.tsx
  src/app/(with-header)/main/components/Recommend.tsx
  src/app/(with-header)/main/components/UserProfileCard.tsx
  src/app/(with-header)/main/page.tsx
  src/app/(with-header)/mypage/components/(problem-tabs)/submitted-card.tsx
  src/app/(with-header)/mypage/components/code-chart.tsx
  src/app/(with-header)/mypage/components/problem-tabs.tsx
  src/app/(with-header)/mypage/components/tag-chart.tsx
  src/app/(with-header)/mypage/page.tsx
  src/app/(with-header)/recommend/components/color-variants.ts
  src/app/(with-header)/recommend/components/problem-card.tsx
  src/app/(with-header)/recommend/components/recommend-content.tsx
  src/app/(with-header)/recommend/components/recommend-section.tsx
  src/app/_api/instance.ts
  src/app/_api/login/logout.ts
  src/app/_components/Header.tsx
  src/app/_store/use-userStore.ts
  src/app/globals.css
  src/app/hook/user/use-contributions.ts
Labels: 📬 API, 🌏 Deploy, 🎨 Desgin

#70 [bug/logout] 로그아웃 로직 수정
  src/app/_api/login/logout.ts
  src/app/_components/Header.tsx
Labels: 🐞 BugFix

#73 [bug/71] intro이미지 변경, 로그아웃 수정
  public/img/section2.png
  src/app/(no-header)/login/page.tsx
  src/app/_api/login/logout.ts
  src/app/_components/Header.tsx
Labels: 🐞 BugFix

#76 feat: 리스트 중복제거, 모달에서 표시, middleware 추가
  src/app/(with-header)/ai-review/components/ai-code-review-list.tsx
  src/app/(with-header)/ai-review/components/code-review-modal.tsx
  src/app/middleware.ts
Labels: 🐞 BugFix

#77 [bug/fix2] useId store값, 빌드오류 해결
  src/app/(with-header)/ai-review/components/ai-code-review-list.tsx
  src/app/(with-header)/code/[id]/page.tsx
  src/app/(with-header)/code/components/code/CodeReview.tsx
  src/app/(with-header)/code/components/code/Footer.tsx
  src/app/(with-header)/code/components/code/ProblemInfo.tsx
  src/app/(with-header)/layout.tsx
  src/app/(with-header)/main/components/Recommend.tsx
  src/app/(with-header)/main/components/UserProfileCard.tsx
  src/app/(with-header)/main/page.tsx
  src/app/(with-header)/mypage/components/intro-section.tsx
  src/app/(with-header)/mypage/page.tsx
  src/app/(with-header)/page.tsx
  src/app/(with-header)/recommend/components/recommend-content.tsx
  src/app/(with-header)/recommend/page.tsx
  src/app/(with-header)/review-list/page.tsx
  src/app/_api/user/getMyInfo.ts
  src/app/_components/Header.tsx
  src/app/_store/use-userStore.ts
Labels: 🐞 BugFix, 🌏 Deploy

#80 [bug/fix] layout useEffect삭제, hook 옵션 추가
  src/app/(no-header)/profile/page.tsx
  src/app/(with-header)/layout.tsx
  src/app/(with-header)/main/page.tsx
  src/app/hook/problem/use-latest-reivewed-1.ts
Labels: 🐞 BugFix

#81 [bug/fix] redirect 주소변경
  src/app/(with-header)/layout.tsx
  src/app/(with-header)/page.tsx
Labels: 🐞 BugFix, 🌏 Deploy
